language: python

python:
  - "3.7"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install coverage
  
before_script:
  - uname -a
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - printenv |sort

  
script:
  - coverage run python setup.py test

after_success:
  - coverage report
	