language: python
python:
	- "3.7"

branches:
	only:
		- master
		
install:
	- pip install -r requirements.txt
	- pip install coverage 
script:
	- coverage run python setup test
	


after_success:
	coverage report
	